name: Python application

on:
  [push]

permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_NAME: site-django-pycidcd-dev1 # Set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './src/django-app' # Set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    
    - uses: azure/login@v3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Python 3.x
      uses: actions/setup-python@v6
      with:
        python-version: 3.x

    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        # Automatically caches the uv package store between CI runs
        enable-cache: true
      
    - name: Create virtual environment and install dependencies
      run: |
        uv venv src/django-app/antenv
        source src/django-app/antenv/bin/activate
        uv sync --project src/django-app/pyproject.toml --no-dev --frozen
        
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: logout
      run: |
        az logout
